In [45]:
import numpy as np

In [61]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("array:",arr)

array: [ 1  2  3  4  5  6  7  8  9 10]


In [6]:
arr1=np.array([1,2,3,4])
print("1D:")
print(arr1)

1D:
[1 2 3 4]


In [28]:
arr2=np.array([[2,3,4,5],[1,4,8,8]])
print("2D:")
print(arr2)

2D:
[[2 3 4 5]
 [1 4 8 8]]


In [35]:
arr3= np.array([[1,2,3],[4,5,6],[7,8,9]])
print("3D:")
print(arr3)

3D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
#indexing
print("first element:")
print(arr[0])

first element:
1


In [39]:
print("backward element:")
print(arr[-1])

backward element:
6


In [63]:
#advanced  indexing
indicats=np.array([0,2,4,5])
print("element:",arr[indicats])

element: [1 3 5 6]


In [65]:
arr[0] =11
print("update array:",arr)

update array: [11  2  3  4  5  6  7  8  9 10]
